// Data for Seoul Date Itinerary
const ORAKAI_LOCATION = {
    name: "Orakai Insadong Suites",
    lat: 37.5741,
    lng: 126.9854,
    address: "18 Insadong 4-Gil, Jongno-gu, Seoul"
};

const restaurants = [
    {
        name: "발우공양 (Balwoo Gongyang)",
        category: "Hanjeongsik / Temple Food",
        area: "Jongno",
        distance: "8 min walk",
        bestDay: "Feb 11",
        description: "Michelin-starred temple cuisine in serene setting with private rooms available. Buddhist vegetarian courses showcase seasonal ingredients without raw seafood",
        platform: "Catchtable",
        link: "https://www.catchtable.co.kr/",
        rating: "⭐4.4/5",
        lat: 37.5741,
        lng: 126.9854,
        type: "restaurant"
    },
    {
        name: "미쉬매쉬 (Mishmash)",
        category: "Hansik",
        area: "Bukchon",
        distance: "5-8 min taxi",
        bestDay: "Feb 11",
        description: "Intimate Hanok with palace wall views offering creative Korean cuisine. Chef-led tasting menu with carefully sourced ingredients",
        platform: "Catchtable",
        link: "https://www.catchtable.co.kr/",
        rating: "⭐4.4/5",
        lat: 37.582100000000004,
        lng: 126.9934,
        type: "restaurant"
    },
    {
        name: "온6.5 (On6.5)",
        category: "Makgeolli Bar",
        area: "Bukchon",
        distance: "5-8 min taxi",
        bestDay: "Feb 11",
        description: "Sophisticated modern space with creative fermented dishes and premium makgeolli pairings. Unique atmosphere in renovated Hanok",
        platform: "Catchtable",
        link: "https://www.catchtable.co.kr/",
        rating: "⭐4.4/5",
        lat: 37.5901,
        lng: 127.0014,
        type: "restaurant"
    },
    {
        name: "산촌 (Sanchon)",
        category: "Hanjeongsik / Temple Food",
        area: "Insadong",
        distance: "5 min walk",
        bestDay: "Feb 11",
        description: "Beautiful traditional house with plant-filled courtyard and occasional cultural performances. Seasonal temple food without raw seafood",
        platform: "TripAdvisor",
        link: "https://www.tripadvisor.com/Search?q=Sanchon+Insadong+Seoul",
        rating: "⭐4.4/5",
        lat: 37.5981,
        lng: 127.0094,
        type: "restaurant"
    },
    {
        name: "목멱산방 (Mokmyeoksanbang)",
        category: "Hansik / View Restaurant",
        area: "Namsan",
        distance: "10 min taxi",
        bestDay: "Feb 11",
        description: "🏔️ NAMSAN FOREST VIEW - Award-winning bibimbap on Namsan slopes with nature views away from city noise. Intimate setting perfect for couples",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Mokmyeoksanbang+Namsan+Seoul",
        rating: "⭐4.4/5",
        lat: 37.6061,
        lng: 127.0174,
        type: "restaurant"
    },
    {
        name: "진진 (Jin Jin)",
        category: "Korean BBQ",
        area: "Jongno",
        distance: "10 min walk",
        bestDay: "Feb 11",
        description: "Premium Korean BBQ with intimate booth seating and excellent service. High-quality beef from trusted suppliers",
        platform: "Catchtable",
        link: "https://www.catchtable.co.kr/",
        rating: "⭐4.4/5",
        lat: 37.6141,
        lng: 127.0254,
        type: "restaurant"
    },
    {
        name: "궁 (Koong)",
        category: "Hanjeongsik",
        area: "Insadong",
        distance: "7 min walk",
        bestDay: "Either",
        description: "Elegant traditional Korean course meals in refined Hanok atmosphere. Multi-course meal showcasing various cooking techniques without raw ingredients",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Koong+Restaurant+Insadong",
        rating: "⭐4.4/5",
        lat: 37.6221,
        lng: 127.0334,
        type: "restaurant"
    },
    {
        name: "남산서울타워 한쿡 (N Seoul Tower Hancook)",
        category: "View Restaurant",
        area: "Namsan",
        distance: "15 min taxi",
        bestDay: "Feb 11",
        description: "🌆 NAMSAN VIEW HIGHLIGHT - Rotating restaurant with panoramic Seoul views serving Korean fusion cuisine. Romantic setting with food presentation focused on aesthetic beauty",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/N+Seoul+Tower+Hancook",
        rating: "⭐4.4/5",
        lat: 37.6301,
        lng: 127.0414,
        type: "restaurant"
    },
    {
        name: "꽃, 밥에 피다 (A Flower Blossom on the Rice)",
        category: "Hansik / Organic",
        area: "Insadong",
        distance: "5 min walk",
        bestDay: "Feb 10",
        description: "Michelin Green Star organic restaurant with calm, healing atmosphere. Farm-to-table meals with seasonal vegetables and no raw seafood. ⭐4.6/5",
        platform: "Catchtable",
        link: "https://www.catchtable.co.kr/",
        rating: "⭐4.4/5",
        lat: 37.6381,
        lng: 127.04939999999999,
        type: "restaurant"
    },
    {
        name: "개성만두 궁 (Gaeseong Mandu Koong)",
        category: "Hansik / Dumpling",
        area: "Insadong",
        distance: "3 min walk",
        bestDay: "Feb 10",
        description: "Cozy Hanok serving warm comfort food ideal for gentle arrival evening. Famous for handmade dumplings with various fillings. ⭐4.4/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Gaeseong+Mandu+Koong+Insadong",
        rating: "⭐4.4/5",
        lat: 37.646100000000004,
        lng: 127.0574,
        type: "restaurant"
    },
    {
        name: "지리산 (Jirisan)",
        category: "Hansik / Tofu",
        area: "Insadong",
        distance: "5 min walk",
        bestDay: "Feb 10",
        description: "Traditional tofu-focused restaurant with quiet ambiance and easy-to-digest meals. All dishes centered around silken tofu preparations. ⭐4.5/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Jirisan+Restaurant+Insadong",
        rating: "⭐4.4/5",
        lat: 37.5711,
        lng: 126.9824,
        type: "restaurant"
    },
    {
        name: "옛날집 (Yetnalzip)",
        category: "Hansik",
        area: "Bukchon",
        distance: "8 min walk",
        bestDay: "Feb 11",
        description: "Charming restaurant in historic Hanok with galbi and bulgogi specials. Homestyle Korean cooking with family recipes. ⭐4.3/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Yetnalzip+Bukchon",
        rating: "⭐4.4/5",
        lat: 37.579100000000004,
        lng: 126.9904,
        type: "restaurant"
    },
    {
        name: "순우 (Sunwoo)",
        category: "Soups & Broths",
        area: "Jongno",
        distance: "6 min walk",
        bestDay: "Feb 11",
        description: "Neighborhood favorite specializing in rich broths and stews. Famous for yukgaejang (spicy beef soup) and samgyetang (ginseng chicken). ⭐4.4/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Sunwoo+Restaurant+Jongno",
        rating: "⭐4.4/5",
        lat: 37.5871,
        lng: 126.9984,
        type: "restaurant"
    },
    {
        name: "서울할머니 (Seoul Grandmother)",
        category: "Hansik",
        area: "Insadong",
        distance: "4 min walk",
        bestDay: "Feb 10",
        description: "Traditional neighborhood diner with authentic home-cooked taste. Specializes in seasonable, simple Korean side dishes. ⭐4.2/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Seoul+Grandmother+Insadong",
        rating: "⭐4.4/5",
        lat: 37.5951,
        lng: 127.0064,
        type: "restaurant"
    },
    {
        name: "강강술래 (Ganggangsulrae)",
        category: "Korean Set Meals",
        area: "Bukchon",
        distance: "10 min walk",
        bestDay: "Feb 11",
        description: "Casual restaurant with beautiful Hanok interior and excellent bapsang (set meal) offerings. Known for quality rice and diverse banchan. ⭐4.4/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Ganggangsulrae+Bukchon",
        rating: "⭐4.4/5",
        lat: 37.6031,
        lng: 127.0144,
        type: "restaurant"
    },
    {
        name: "이화 (Ihwa)",
        category: "Jjigae / Stew",
        area: "Jongno",
        distance: "7 min walk",
        bestDay: "Feb 11",
        description: "Popular for galbijjim and jjigae dishes. Cozy interior, generous portions of comfort food. ⭐4.1/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Ihwa+Restaurant+Jongno",
        rating: "⭐4.4/5",
        lat: 37.6111,
        lng: 127.0224,
        type: "restaurant"
    },
    {
        name: "청와대 앞 국밥 (Blue House Area Gugbap)",
        category: "Soup & Rice",
        area: "Jongno",
        distance: "5 min walk",
        bestDay: "Feb 10",
        description: "No-frills local joint famous for ox bone soup and dongtaejjim. Perfect for quick, nourishing meal after travel. ⭐4.3/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Blue+House+Area+Gugbap+Jongno",
        rating: "⭐4.4/5",
        lat: 37.6191,
        lng: 127.0304,
        type: "restaurant"
    },
    {
        name: "느그네 (Neugeune)",
        category: "Korean Fusion",
        area: "Insadong",
        distance: "3 min walk",
        bestDay: "Either",
        description: "Contemporary space serving creative Korean dishes with modern plating. Uses premium ingredients with interesting flavor combinations. ⭐4.3/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Neugeune+Insadong",
        rating: "⭐4.4/5",
        lat: 37.6271,
        lng: 127.0384,
        type: "restaurant"
    },
    {
        name: "도마 (Doma)",
        category: "Korean BBQ",
        area: "Hongdae",
        distance: "20 min subway",
        bestDay: "Feb 12",
        description: "Trendy Korean BBQ spot with interesting cuts and house marinades. Stylish interior and attentive service. ⭐4.4/5",
        platform: "Google Maps",
        link: "https://www.google.com/maps/search/Doma+Korean+BBQ+Hongdae",
        rating: "⭐4.4/5",
        lat: 37.6351,
        lng: 127.04639999999999,
        type: "restaurant"
    }
];

const activities = [
    {
        name: "Gyeongbokgung Palace Tour",
        type: "Historical Site",
        area: "Jongno",
        duration: "1.5-2 hours",
        bestDay: "Feb 11",
        description: "📸 PHOTO SPOT - Stunning photogenic palace with guards ceremony at 10am/2pm/3pm. Beautiful winter light on stone walls, perfect for couples. ⭐4.6/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/Gyeongbokgung+Palace",
        rating: "⭐4.4/5",
        lat: 37.579100000000004,
        lng: 126.9904,
        type: "activity"
    },
    {
        name: "Bukchon Hanok Village Walk",
        type: "Cultural Area",
        area: "Bukchon",
        duration: "1-2 hours",
        bestDay: "Feb 11",
        description: "🎨 STREET ART - Narrow lanes with traditional wooden houses, secret gardens, art galleries and cafes. Incredibly photogenic. ⭐4.5/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Bukchon+Hanok+Village",
        rating: "⭐4.4/5",
        lat: 37.58710000000001,
        lng: 126.99839999999999,
        type: "activity"
    },
    {
        name: "N Seoul Tower & Observatory",
        type: "Landmark",
        area: "Namsan",
        duration: "1-2 hours",
        bestDay: "Feb 11",
        description: "🌆 CITY VIEWS HIGHLIGHT - 360° panoramic views of Seoul, love locks area, and revolving restaurant. Stunning at sunset. ⭐4.5/5",
        bestTime: "Sunset",
        link: "https://www.google.com/maps/place/N+Seoul+Tower",
        rating: "⭐4.4/5",
        lat: 37.5951,
        lng: 127.0064,
        type: "activity"
    },
    {
        name: "Insadong Traditional Shopping District",
        type: "Shopping & Culture",
        area: "Insadong",
        duration: "1.5-2 hours",
        bestDay: "Feb 11",
        description: "Traditional Korean art, antiques, tea houses. Street performances on weekends. ⭐4.3/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Insadong",
        rating: "⭐4.4/5",
        lat: 37.603100000000005,
        lng: 127.0144,
        type: "activity"
    },
    {
        name: "Cheonggyecheon Walk",
        type: "Urban Park",
        area: "Jongno",
        duration: "45 min - 1.5 hours",
        bestDay: "Feb 10",
        description: "💧 STREAM VIEW - Beautiful restored creek running through downtown with walking path, cafes, and art installations. Peaceful escape from city. ⭐4.4/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/place/Cheonggyecheon",
        rating: "⭐4.4/5",
        lat: 37.6111,
        lng: 127.02239999999999,
        type: "activity"
    },
    {
        name: "Myeongdong Shopping Street",
        type: "Shopping District",
        area: "Myeongdong",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "Popular pedestrian street with global brands, Korean beauty products, street food, and bustling energy. ⭐4.2/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Myeongdong",
        rating: "⭐4.4/5",
        lat: 37.6191,
        lng: 127.0304,
        type: "activity"
    },
    {
        name: "Gwangjang Market Morning Visit",
        type: "Market",
        area: "Jongno",
        duration: "1-1.5 hours",
        bestDay: "Feb 10",
        description: "Historic market with street food vendors, textile stalls. Perfect for authentic local experience and tasting pajeon, tteokbokki. ⭐4.3/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/Gwangjang+Market",
        rating: "⭐4.4/5",
        lat: 37.627100000000006,
        lng: 127.0384,
        type: "activity"
    },
    {
        name: "Namsan Parks & Walking Trails",
        type: "Nature",
        area: "Namsan",
        duration: "1-2 hours",
        bestDay: "Either",
        description: "🌲 FOREST VIEWS - Peaceful mountain paths with city views, sculpture parks, and N Tower backdrop. Romantic setting. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Namsan+Park",
        rating: "⭐4.4/5",
        lat: 37.6351,
        lng: 127.04639999999999,
        type: "activity"
    },
    {
        name: "Hyehwa Arts District Exploration",
        type: "Arts & Culture",
        area: "Hyehwa",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "Artistic neighborhood with indie bookstores, galleries, small theaters, unique cafes. Bohemian atmosphere. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Hyehwa+Arts+District",
        rating: "⭐4.4/5",
        lat: 37.643100000000004,
        lng: 127.05439999999999,
        type: "activity"
    },
    {
        name: "Jongmyo Shrine Visit",
        type: "Historical Site",
        area: "Jongno",
        duration: "1 hour",
        bestDay: "Feb 11",
        description: "Ancient royal shrine with peaceful grounds and traditional architecture. Less touristy than Gyeongbokgung. ⭐4.3/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Jongmyo+Shrine",
        rating: "⭐4.4/5",
        lat: 37.65110000000001,
        lng: 127.0624,
        type: "activity"
    },
    {
        name: "Cat Cafes (Bukchon Area)",
        type: "Cafe Experience",
        area: "Bukchon",
        duration: "1-1.5 hours",
        bestDay: "Either",
        description: "Unique Korean cat cafe concept with adorable cats, pastries and beverages. Cozy intimate setting. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/search/Cat+Cafe+Bukchon",
        rating: "⭐4.4/5",
        lat: 37.576100000000004,
        lng: 126.9874,
        type: "activity"
    },
    {
        name: "Ongnyeon Art Hall & Galleries",
        type: "Art & Culture",
        area: "Insadong",
        duration: "1-1.5 hours",
        bestDay: "Feb 11",
        description: "Contemporary art gallery spaces, often free exhibitions. Support emerging Korean artists. ⭐4.2/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Insadong+Art+Museums",
        rating: "⭐4.4/5",
        lat: 37.58410000000001,
        lng: 126.99539999999999,
        type: "activity"
    },
    {
        name: "Jogyesa Temple Visit",
        type: "Religious Site",
        area: "Jongno",
        duration: "45 min",
        bestDay: "Feb 11",
        description: "Beautiful Buddhist temple with peaceful garden, lantern decorations during festival season. ⭐4.3/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/Jogyesa+Temple",
        rating: "⭐4.4/5",
        lat: 37.5921,
        lng: 127.0034,
        type: "activity"
    },
    {
        name: "Buamdong Village Exploration",
        type: "Cultural Area",
        area: "Buamdong",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "🏙️ ROOFTOP VIEWS - Trendy hillside neighborhood with independent shops, galleries, cafes, and sweeping city views. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Buamdong",
        rating: "⭐4.4/5",
        lat: 37.600100000000005,
        lng: 127.0114,
        type: "activity"
    },
    {
        name: "Seongbuk Waterfall Trail",
        type: "Nature Walk",
        area: "Seongbuk",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "🌅 NATURE ESCAPE - Scenic waterfall and stream walk through forest. Hidden gem away from crowds. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/search/Seongbuk+Waterfall+Trail",
        rating: "⭐4.4/5",
        lat: 37.6081,
        lng: 127.01939999999999,
        type: "activity"
    },
    {
        name: "Korean Traditional Music Performance",
        type: "Performance",
        area: "Jongno",
        duration: "1-1.5 hours",
        bestDay: "Feb 11",
        description: "🎵 CULTURAL SHOW - Traditional Korean music and dance performances. Check venue schedules. ⭐4.3/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/search/Korean+Traditional+Music+Performance+Seoul",
        rating: "⭐4.4/5",
        lat: 37.6161,
        lng: 127.0274,
        type: "activity"
    },
    {
        name: "Hongdae Arts & Youth Culture",
        type: "Arts & Culture",
        area: "Hongdae",
        duration: "2-3 hours",
        bestDay: "Feb 12",
        description: "Artsy neighborhood with street art, indie music venues, unique cafes, young creative scene. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Hongdae",
        rating: "⭐4.4/5",
        lat: 37.624100000000006,
        lng: 127.0354,
        type: "activity"
    },
    {
        name: "Changdeokgung Palace & Secret Garden",
        type: "Historical Site",
        area: "Jongno",
        duration: "2-2.5 hours",
        bestDay: "Feb 11",
        description: "UNESCO site with beautiful palace and famous Secret Garden (Huwon). More secluded than Gyeongbokgung. ⭐4.6/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/Changdeokgung+Palace",
        rating: "⭐4.4/5",
        lat: 37.6321,
        lng: 127.04339999999999,
        type: "activity"
    },
    {
        name: "Samcheong-dong Art & Antique Street",
        type: "Shopping & Culture",
        area: "Jongno",
        duration: "1.5 hours",
        bestDay: "Feb 12",
        description: "Eclectic mix of antique shops, galleries, design stores, cafes. Charming bohemian street. ⭐4.3/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Samcheong-dong",
        rating: "⭐4.4/5",
        lat: 37.640100000000004,
        lng: 127.05139999999999,
        type: "activity"
    },
    {
        name: "Songpa-gu Lotte World Area",
        type: "Shopping & Entertainment",
        area: "Songpa",
        duration: "2-3 hours",
        bestDay: "Feb 12",
        description: "Modern shopping complex, entertainment, restaurants. Good if wanting contemporary Seoul experience. ⭐4.2/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Lotte+World",
        rating: "⭐4.4/5",
        lat: 37.64810000000001,
        lng: 127.0594,
        type: "activity"
    },
    {
        name: "Naksan Park Sunset Spot",
        type: "Viewpoint",
        area: "Jongno",
        duration: "1 hour",
        bestDay: "Feb 11",
        description: "🌅 SUNSET HIGHLIGHT - Hidden gem with panoramic city views and romantic sunset spot. Less crowded than N Tower. ⭐4.5/5",
        bestTime: "Sunset",
        link: "https://www.google.com/maps/place/Naksan+Park",
        rating: "⭐4.4/5",
        lat: 37.573100000000004,
        lng: 126.9844,
        type: "activity"
    },
    {
        name: "Bookstore Cafe Experience (Gyeongui Line)",
        type: "Cafe & Culture",
        area: "Hongdae",
        duration: "1-1.5 hours",
        bestDay: "Feb 12",
        description: "Unique bookstore cafes along converted railway. Browse rare books, sip coffee, artistic atmosphere. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/search/Bookstore+Cafe+Gyeongui+Line",
        rating: "⭐4.4/5",
        lat: 37.581100000000006,
        lng: 126.99239999999999,
        type: "activity"
    },
    {
        name: "National Museum of Korea",
        type: "Museum",
        area: "Ichon",
        duration: "2-3 hours",
        bestDay: "Feb 12",
        description: "Comprehensive Korean history and art museum. World-class collections, peaceful gardens. ⭐4.5/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/National+Museum+of+Korea",
        rating: "⭐4.4/5",
        lat: 37.5891,
        lng: 127.0004,
        type: "activity"
    },
    {
        name: "Seokchon-dong Hanok Tour",
        type: "Cultural Area",
        area: "Jongno",
        duration: "1-1.5 hours",
        bestDay: "Feb 11",
        description: "Traditional village near Changdeokgung with historic hanok houses, restaurants, quieter than Bukchon. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Seokchon-dong",
        rating: "⭐4.4/5",
        lat: 37.597100000000005,
        lng: 127.0084,
        type: "activity"
    },
    {
        name: "Itaewon International District Walk",
        type: "Shopping & Dining",
        area: "Itaewon",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "Diverse international shops, restaurants, nightlife district. Good for contemporary cosmopolitan Seoul. ⭐4.3/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/place/Itaewon",
        rating: "⭐4.4/5",
        lat: 37.6051,
        lng: 127.01639999999999,
        type: "activity"
    },
    {
        name: "Tea House Experience (Traditional)",
        type: "Cafe Experience",
        area: "Insadong",
        duration: "1-1.5 hours",
        bestDay: "Feb 11",
        description: "🫖 CULTURAL EXPERIENCE - Traditional Korean tea ceremony and herbal tea tasting in historic setting. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/search/Traditional+Tea+House+Insadong",
        rating: "⭐4.4/5",
        lat: 37.6131,
        lng: 127.0244,
        type: "activity"
    },
    {
        name: "Deoksugung Palace & Museum",
        type: "Historical Site",
        area: "Jongno",
        duration: "1.5 hours",
        bestDay: "Feb 11",
        description: "Western-influenced palace with changing of guards ceremony. Smaller and less crowded. ⭐4.2/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/Deoksugung+Palace",
        rating: "⭐4.4/5",
        lat: 37.621100000000006,
        lng: 127.0324,
        type: "activity"
    },
    {
        name: "Myeongdong Street Art Murals",
        type: "Photo Spot",
        area: "Myeongdong",
        duration: "45 min",
        bestDay: "Feb 12",
        description: "📸 STREET ART - Hidden alleyways with colorful murals and graffiti art. Instagram-worthy spots. ⭐4.2/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Myeongdong",
        rating: "⭐4.4/5",
        lat: 37.6291,
        lng: 127.04039999999999,
        type: "activity"
    },
    {
        name: "Garosu-gil Luxury Shopping District",
        type: "Shopping District",
        area: "Gangnam",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "Upscale shopping street with international brands, cafes, galleries. Modern Seoul experience. ⭐4.3/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Garosu-gil",
        rating: "⭐4.4/5",
        lat: 37.637100000000004,
        lng: 127.04839999999999,
        type: "activity"
    },
    {
        name: "Zaha Hadid's Dongdaemun Design Plaza",
        type: "Architecture",
        area: "Dongdaemun",
        duration: "1-1.5 hours",
        bestDay: "Feb 12",
        description: "🏛️ MODERN ARCHITECTURE - Iconic futuristic building with design exhibitions, fashion shows. ⭐4.4/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Dongdaemun+Design+Plaza",
        rating: "⭐4.4/5",
        lat: 37.645100000000006,
        lng: 127.0564,
        type: "activity"
    },
    {
        name: "Seocho-dong Gangnam Experience",
        type: "Modern District",
        area: "Gangnam",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "Shopping, Korean entertainment venues (noraebang), cosmopolitan vibes. See modern developed Seoul. ⭐4.2/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/place/Gangnam+District",
        rating: "⭐4.4/5",
        lat: 37.570100000000004,
        lng: 126.9814,
        type: "activity"
    },
    {
        name: "Evening Han River Park Bike Ride",
        type: "Nature & Recreation",
        area: "Various",
        duration: "1-1.5 hours",
        bestDay: "Feb 11",
        description: "🚴 OUTDOOR ACTIVITY - Scenic bike path along Han River with evening city lights. Romantic nighttime experience. ⭐4.5/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/search/Han+River+Park+Biking",
        rating: "⭐4.4/5",
        lat: 37.578100000000006,
        lng: 126.98939999999999,
        type: "activity"
    },
    {
        name: "Changgyeonggung Palace & Botanical Garden",
        type: "Historical Site",
        area: "Jongno",
        duration: "1.5-2 hours",
        bestDay: "Feb 11",
        description: "Beautiful palace with excellent botanical garden. Winter foliage stunning, less crowded than major palaces. ⭐4.3/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/place/Changgyeonggung+Palace",
        rating: "⭐4.4/5",
        lat: 37.5861,
        lng: 126.9974,
        type: "activity"
    },
    {
        name: "Ssamzie-gil Art Complex (Insadong)",
        type: "Arts & Shopping",
        area: "Insadong",
        duration: "1-1.5 hours",
        bestDay: "Feb 11",
        description: "Eclectic art and design complex with contemporary galleries, fashion boutiques, creative restaurants. ⭐4.3/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Ssamzie-gil",
        rating: "⭐4.4/5",
        lat: 37.594100000000005,
        lng: 127.0054,
        type: "activity"
    },
    {
        name: "Coffee Specialty Cafe Hopping",
        type: "Cafe Culture",
        area: "Bukchon/Insadong",
        duration: "2 hours",
        bestDay: "Feb 12",
        description: "☕ SEOUL CULTURE - Visit 3-4 specialty coffee roasteries and cafes. Seoul's famous coffee culture. ⭐4.5/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/search/Specialty+Coffee+Cafe+Seoul",
        rating: "⭐4.4/5",
        lat: 37.6021,
        lng: 127.01339999999999,
        type: "activity"
    },
    {
        name: "K-pop Noraebang (Karaoke) Night",
        type: "Entertainment",
        area: "Gangnam/Hongdae",
        duration: "1.5-2 hours",
        bestDay: "Feb 11",
        description: "🎤 FUN EXPERIENCE - Korean karaoke with private rooms, high-tech systems, vast song library. Couples highlight! ⭐4.6/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/search/Noraebang+Karaoke+Seoul",
        rating: "⭐4.4/5",
        lat: 37.6101,
        lng: 127.0214,
        type: "activity"
    },
    {
        name: "Jangchung-dong Shopping & Restaurants",
        type: "Shopping District",
        area: "Jung",
        duration: "1.5 hours",
        bestDay: "Feb 12",
        description: "Local neighborhood with unique boutiques, cafes, restaurants. Authentic Seoul feel away from tourists. ⭐4.2/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/place/Jangchung-dong",
        rating: "⭐4.4/5",
        lat: 37.618100000000005,
        lng: 127.0294,
        type: "activity"
    },
    {
        name: "DMZ & Korean War History Tour (Full Day)",
        type: "Historical Tour",
        area: "Demilitarized Zone",
        duration: "6-8 hours",
        bestDay: "Feb 12",
        description: "Sobering tour of divided Korea's history. Requires passport. Profound historical experience. ⭐4.4/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/search/DMZ+Tour+Seoul",
        rating: "⭐4.4/5",
        lat: 37.6261,
        lng: 127.03739999999999,
        type: "activity"
    },
    {
        name: "Kimchi Making Class",
        type: "Cultural Workshop",
        area: "Insadong/Jongno",
        duration: "2-2.5 hours",
        bestDay: "Feb 11",
        description: "🥬 COOKING CLASS - Learn traditional kimchi making from local chef. Hands-on, fun couples activity. ⭐4.5/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/search/Kimchi+Making+Class+Seoul",
        rating: "⭐4.4/5",
        lat: 37.634100000000004,
        lng: 127.04539999999999,
        type: "activity"
    },
    {
        name: "Korean Beauty & Spa Experience",
        type: "Wellness",
        area: "Myeongdong/Gangnam",
        duration: "1.5-2 hours",
        bestDay: "Feb 12",
        description: "💆 RELAXATION - Visit Korean sauna/spa, sheet mask facial, or couples massage. Pure pampering. ⭐4.5/5",
        bestTime: "Afternoon",
        link: "https://www.google.com/maps/search/Korean+Spa+Seoul",
        rating: "⭐4.4/5",
        lat: 37.642100000000006,
        lng: 127.0534,
        type: "activity"
    },
    {
        name: "Hanbok Rental & Palace Photo",
        type: "Cultural Experience",
        area: "Insadong/Bukchon",
        duration: "2-3 hours",
        bestDay: "Feb 11",
        description: "👗 PHOTO EXPERIENCE - Rent traditional hanbok dress, get professional photos at palaces. Memorable keepsake. ⭐4.6/5",
        bestTime: "Morning",
        link: "https://www.google.com/maps/search/Hanbok+Rental+Seoul",
        rating: "⭐4.4/5",
        lat: 37.5671,
        lng: 126.9784,
        type: "activity"
    },
    {
        name: "Blind Date Restaurant (K-Drama Style)",
        type: "Dining Experience",
        area: "Various",
        duration: "1.5-2 hours",
        bestDay: "Feb 11",
        description: "🎬 K-DRAMA EXPERIENCE - Trendy concept where you dine behind screens, fun interactive twist. ⭐4.3/5",
        bestTime: "Evening",
        link: "https://www.google.com/maps/search/Blind+Date+Restaurant+Seoul",
        rating: "⭐4.4/5",
        lat: 37.575100000000006,
        lng: 126.98639999999999,
        type: "activity"
    },
];

const routePlans = {
    feb10: {
        title: "Feb 10 - Arrival Day",
        activities: [
            { time: "15:00", name: "Check-in at Orakai", description: "Rest and freshen up" },
            { time: "17:30", name: "Evening Walk in Insadong", description: "Explore traditional shops and street" },
            { time: "19:00", name: "Casual Dinner Nearby", description: "Light meal to adjust to timezone" },
            { time: "21:00", name: "Early Rest", description: "Good sleep for tomorrow" }
        ]
    },
    feb11: {
        title: "Feb 11 - Main Date Day",
        activities: [
            { time: "09:00", name: "Morning Date Start", description: "Breakfast near hotel" },
            { time: "10:00", name: "First Activity", description: "Check selected activities" },
            { time: "12:30", name: "Lunch", description: "Selected restaurant" },
            { time: "14:00", name: "Afternoon Activity", description: "Continue exploration" },
            { time: "18:00", name: "Dinner", description: "Romantic dinner at selected restaurant" },
            { time: "20:00", name: "Evening Activity", description: "Night stroll or special experience" }
        ]
    },
    feb12: {
        title: "Feb 12 - Flexible Day",
        activities: [
            { time: "09:00", name: "Morning Breakfast", description: "Relaxed start" },
            { time: "10:30", name: "Shopping or Activity", description: "Based on preference" },
            { time: "13:00", name: "Lunch", description: "Try remaining restaurant" },
            { time: "14:30", name: "Last-minute Exploration", description: "Favorite spots revisit" },
            { time: "18:00", name: "Farewell Dinner", description: "Special goodbye meal" },
            { time: "20:00", name: "Pack and Rest", description: "Prepare for departure" }
        ]
    }
};
